test connectivity to ec2 part 5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,27 +18,28 @@ jobs:
         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
-
-    - name: Install requests library
-      run: |
-        python -m pip install --upgrade pip
-        pip install requests
-
-    - name: Get Runner IP
-      run: |
-        curl -sS https://api.ipify.org > runner_ip.txt
-        echo "Runner IP: $(cat runner_ip.txt)"
-
-    - name: Upload IP address file
-      uses: actions/upload-artifact@v2
-      with:
-        name: runner-ip
-        path: runner_ip.txt
     
-    # - name: Set up SSH key
-    #   uses: actions/checkout@v3
-    #   with:
-    #     private-key: ${{ secrets.UD_SSH_KEY }}
+    - name: Set up SSH key
+      uses: actions/checkout@v3
+      with:
+        private-key: ${{ secrets.UD_SSH_KEY }}
+
+    - name: Test SSH connection to EC2
+      run: |
+        #!/bin/bash
+
+        # Replace placeholders with your actual values
+        HOST=ec2-3-8-184-137.eu-west-2.compute.amazonaws.com
+        USER=ec2-user
+        KEY_PATH=${{ secrets.UD_SSH_KEY_PATH }}/umrahdeals-kp.pem
+
+        # Attempt SSH connection
+        if ssh -i $KEY_PATH $USER@$HOST "echo SSH connection successful!" &> /dev/null; then
+          echo "SSH connection to $HOST successful!"
+        else
+          echo "SSH connection to $HOST failed!"
+          exit 1
+        fi
 
     # - name: Copy backend files to EC2 instance
     #   run: scp -i ${{ secrets.UD_SSH_KEY }} -r -o StrictHostKeyChecking=no ~/Documents/projects/umrahdeals/server/ ec2-user@3.8.184.137:~/umrahdeals/
