test connectivity to ec2 part 4

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,12 +25,21 @@ jobs:
         private-key: ${{ secrets.UD_SSH_KEY }}
 
     - name: Test SSH connection to EC2
-      uses: nhost/nhost-deploy@v1
-      with:
-        hostname: ec2-3-8-184-137.eu-west-2.compute.amazonaws.com
-        username: ec2-user
-        key: ${{ secrets.UD_SSH_KEY }}
-        command: "echo SSH connection successful!"
+      run: |
+        #!/bin/bash
+
+        # Replace placeholders with your actual values
+        HOST=ec2-3-8-184-137.eu-west-2.compute.amazonaws.com
+        USER=ec2-user
+        KEY_PATH=${{ secrets.UD_SSH_KEY_PATH }}/umrahdeals-kp.pem
+
+        # Attempt SSH connection
+        if ssh -i $KEY_PATH $USER@$HOST "echo SSH connection successful!" &> /dev/null; then
+          echo "SSH connection to $HOST successful!"
+        else
+          echo "SSH connection to $HOST failed!"
+          exit 1
+        fi
 
 
     # - name: Set up SSH key
